
import React, { useState, useMemo, useCallback } from 'react';
import Card from './Card';
import { vfxDatabase } from '../data/vfxDatabase';
import { VFXComplexity, Shot } from '../types';
import { getColorBibleAnalysis } from '../services/geminiService';

const MarkdownRenderer: React.FC<{ content: string }> = ({ content }) => {
    return <div className="prose prose-invert prose-sm max-w-none text-vanguard-text whitespace-pre-wrap" dangerouslySetInnerHTML={{ __html: content.replace(/### (.*?)\n/g, '<h3>$1</h3>').replace(/\n/g, '<br />') }} />;
};

interface ColorVFXHubProps {
  shots: Shot[];
  lockedStoryboard: Record<string, string>;
}

const ColorVFXHub: React.FC<ColorVFXHubProps> = ({ shots, lockedStoryboard }) => {
  const [activeTab, setActiveTab] = useState<'vfx' | 'color'>('vfx');
  const lockedShots = useMemo(() => shots.filter(shot => lockedStoryboard[shot.id]), [shots, lockedStoryboard]);

  const [selectedShotId, setSelectedShotId] = useState<string>(lockedShots[0]?.id || '');
  const [analysis, setAnalysis] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [gradedPreview, setGradedPreview] = useState<string | null>(null);

  const handleAnalyzeColor = useCallback(async () => {
    if (!selectedShotId) return;
    const shot = shots.find(s => s.id === selectedShotId);
    if (!shot) return;

    setIsLoading(true);
    setAnalysis('');
    setGradedPreview(null);
    try {
        const stream = getColorBibleAnalysis(shot.scene);
        let fullResponse = '';
        for await (const chunk of stream) {
            fullResponse += chunk;
        }
        setAnalysis(fullResponse);
    } catch (e) {
        setAnalysis("Failed to get color analysis.");
    } finally {
        setIsLoading(false);
    }
  }, [selectedShotId, shots]);
  
  const handleExportLUT = () => {
    // This is a placeholder for a complex function.
    // In a real app, this would generate a .cube file based on the analysis.
    const lutContent = `
# Generated by Vanguard AI Colorist
TITLE "VFX_Lookbook_AI_Grade"
LUT_3D_SIZE 32
0.0 0.0 0.0
... more LUT data ...
1.0 1.0 1.0
    `.trim();
    const blob = new Blob([lutContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${selectedShotId}_grade.cube`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const complexityColor: Record<VFXComplexity, string> = {
    'Simple': 'bg-vanguard-green/20 text-vanguard-green',
    'Medium': 'bg-vanguard-yellow/20 text-yellow-400',
    'Complex': 'bg-vanguard-red/20 text-vanguard-red',
  }

  return (
    <div className="space-y-8 h-full flex flex-col">
      <div>
        <h1 className="text-3xl font-bold text-vanguard-text">Color & VFX Hub</h1>
        <p className="text-vanguard-text-secondary mt-2">Manage your film's visual effects pipeline and develop the color grading strategy for each scene.</p>
      </div>

      <div className="flex border-b border-vanguard-bg-tertiary">
        <button onClick={() => setActiveTab('vfx')} className={`py-2 px-4 text-sm font-semibold ${activeTab === 'vfx' ? 'text-vanguard-accent border-b-2 border-vanguard-accent' : 'text-vanguard-text-secondary'}`}>VFX Shot Tracker</button>
        <button onClick={() => setActiveTab('color')} className={`py-2 px-4 text-sm font-semibold ${activeTab === 'color' ? 'text-vanguard-accent border-b-2 border-vanguard-accent' : 'text-vanguard-text-secondary'}`}>AI Colorist & LUTs</button>
      </div>

      {activeTab === 'vfx' && (
        <Card title="VFX Shot Database" className="flex-1 flex flex-col">
          <div className="overflow-y-auto flex-1">
            <table className="w-full text-left text-sm">
              <thead className="sticky top-0 bg-vanguard-bg-secondary">
                <tr className="border-b border-vanguard-bg-tertiary">
                  {['id', 'scene', 'description', 'complexity', 'budget', 'timeline'].map(col => (
                    <th key={col} className="py-3 px-4 uppercase tracking-wider text-xs text-vanguard-text-secondary">{col}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {vfxDatabase.map(shot => (
                  <tr key={shot.id} className="border-b border-vanguard-bg-tertiary hover:bg-vanguard-bg-tertiary/50">
                    <td className="py-3 px-4 font-mono text-xs">{shot.id}</td>
                    <td className="py-3 px-4">{shot.scene}</td>
                    <td className="py-3 px-4 max-w-sm truncate">{shot.description}</td>
                    <td className="py-3 px-4">
                      <span className={`px-2 py-1 text-xs font-semibold rounded-full ${complexityColor[shot.complexity]}`}>{shot.complexity}</span>
                    </td>
                    <td className="py-3 px-4">{shot.budget}</td>
                    <td className="py-3 px-4">{shot.timeline}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      )}

      {activeTab === 'color' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <Card title="AI Colorist Analysis">
               <div className="flex items-center space-x-4 mb-4">
                <label htmlFor="shot-select">Select Shot:</label>
                <select id="shot-select" value={selectedShotId} onChange={e => setSelectedShotId(e.target.value)} className="bg-vanguard-bg-tertiary p-2 rounded-md">
                  {lockedShots.map(shot => <option key={shot.id} value={shot.id}>{shot.id}</option>)}
                </select>
                <button onClick={handleAnalyzeColor} disabled={isLoading || !selectedShotId} className="bg-vanguard-accent hover:bg-vanguard-accent-hover text-white font-bold py-2 px-4 rounded-lg disabled:opacity-50">
                    {isLoading ? 'Analyzing...' : `Analyze Color`}
                </button>
                 <button onClick={handleExportLUT} disabled={!analysis} className="bg-vanguard-bg-tertiary hover:bg-vanguard-bg-secondary text-white font-bold py-2 px-4 rounded-lg disabled:opacity-50">
                    Export .cube LUT
                </button>
              </div>
              <div className="mt-4 p-4 bg-vanguard-bg rounded-md min-h-[200px] max-h-[50vh] overflow-y-auto">
                  {isLoading && <p>AI Colorist is analyzing the lookbook...</p>}
                  {!isLoading && !analysis && <p>Select a locked shot and click Analyze to get color grading guidance.</p>}
                  {analysis && <MarkdownRenderer content={analysis} />}
              </div>
            </Card>
             <Card title="Graded Preview">
                <div className="aspect-video bg-vanguard-bg rounded-lg flex items-center justify-center">
                    {selectedShotId && lockedStoryboard[selectedShotId] ? (
                        <img 
                            src={`data:image/png;base64,${lockedStoryboard[selectedShotId]}`} 
                            alt="Graded Preview" 
                            className="max-h-full max-w-full object-contain rounded-md"
                            style={{ filter: analysis ? 'saturate(0.8) contrast(1.1) brightness(0.95)' : 'none' }}
                        />
                    ) : <p className="text-vanguard-text-secondary">Select a shot to see preview.</p>}
                </div>
                <p className="text-xs text-center mt-2 text-vanguard-text-secondary">A simplified preview of the AI's suggested color grade.</p>
            </Card>
        </div>
      )}
    </div>
  );
};

export default ColorVFXHub;
